import type { CSSProperties } from "react";

export const framePresets: Record<string, CSSProperties> = {
  default: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    alignContent: "center",
    justifyContent: "center",
    gap: "1rem",
    width: "100%",
    padding: "clamp(1rem, 5vw, 2.5rem)",
    minHeight: "16rem",
  },
  "default-stacked": {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "1rem",
    width: "100%",
    padding: "clamp(1rem, 5vw, 2.5rem)",
    minHeight: "16rem",
  },
  "default-tall": {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "center",
    gap: "1rem",
    width: "100%",
    padding: "clamp(1rem, 5vw, 2.5rem)",
    minHeight: "24rem",
  },
  // A centered single column whose content area is exactly max-w-sm, so form
  // examples don't need width utilities in their markup.
  form: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    gap: "1rem",
    width: "100%",
    maxWidth: "29rem",
    marginInline: "auto",
    padding: "clamp(1rem, 5vw, 2.5rem)",
    minHeight: "12rem",
  },
  // Centered columns with a max width, so examples need no width utilities:
  // default-tall's height at each component's natural reading width.
  collapsible: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    gap: "1rem",
    width: "100%",
    maxWidth: "33rem",
    marginInline: "auto",
    padding: "clamp(1rem, 5vw, 2.5rem)",
    minHeight: "24rem",
  },
  accordion: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    gap: "1rem",
    width: "100%",
    maxWidth: "37rem",
    marginInline: "auto",
    padding: "clamp(1rem, 5vw, 2.5rem)",
    minHeight: "24rem",
  },
  // Like form, sized so card examples need no width utilities: the content
  // area is exactly max-w-sm.
  card: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    gap: "1rem",
    width: "100%",
    maxWidth: "29rem",
    marginInline: "auto",
    padding: "clamp(1rem, 5vw, 2.5rem)",
    minHeight: "16rem",
  },
  // Like form, but top-aligned so floating panels have room to open below.
  "form-start": {
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
    width: "100%",
    maxWidth: "29rem",
    marginInline: "auto",
    padding: "clamp(1rem, 5vw, 2.5rem)",
    minHeight: "24rem",
  },
  popover: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "flex-start",
    justifyContent: "center",
    gap: "1rem",
    width: "100%",
    padding: "clamp(1rem, 5vw, 2.5rem)",
    minHeight: "24rem",
  },
  dialog: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "center",
    gap: "1rem",
    width: "100%",
    padding: "clamp(1rem, 5vw, 2.5rem)",
    minHeight: "36rem",
  },
  alert: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    gap: "1rem",
    width: "100%",
    maxWidth: "33rem",
    marginInline: "auto",
    padding: "clamp(1rem, 5vw, 2.5rem)",
    minHeight: "12rem",
  },
  item: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    gap: "1.5rem",
    width: "100%",
    maxWidth: "33rem",
    marginInline: "auto",
    padding: "clamp(1rem, 5vw, 2.5rem)",
    minHeight: "16rem",
  },
  empty: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    width: "100%",
    maxWidth: "48rem",
    marginInline: "auto",
    padding: "clamp(1rem, 5vw, 2.5rem)",
    minHeight: "28rem",
  },
  skeleton: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    gap: "1rem",
    width: "100%",
    maxWidth: "33rem",
    marginInline: "auto",
    padding: "clamp(1rem, 5vw, 2.5rem)",
    minHeight: "12rem",
  },
  carousel: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    padding: "clamp(1rem, 5vw, 2.5rem)",
    minHeight: "30rem",
  },
  command: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    padding: "clamp(1rem, 5vw, 2.5rem)",
    minHeight: "26rem",
  },
  drawer: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "center",
    gap: "1rem",
    width: "100%",
    padding: "clamp(1rem, 5vw, 2.5rem)",
    minHeight: "667px",
  },
  sheet: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "center",
    gap: "1rem",
    width: "100%",
    padding: "clamp(1rem, 5vw, 2.5rem)",
    minHeight: "667px",
  },
  sidebar: {
    minHeight: "667px",
  },
};
